layout_spectrum: 1
typography_spectrum: 0.6766919
color:
  saturation: 0.1541219
  brandStrength: 0.8172043
  lightness: 0.06272402
  brandColors:
    - '#2E4380'
    - '#1F2028'
    - '#BDC5D7'
    - '#FFFCFA'
  rhythmicContrast: 0.2706093
name: herrbrendel
